name: Hello World CI

on:
  push:
    branches: [main]

jobs:
  run-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Ejecutar script Hello World
        run: node hello.js
